name: Testing
on:
  pull_request:
    branches: [main]
concurrency:
  # Rerun check when the PR is updated, https://stackoverflow.com/a/72408109
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm build
          start: pnpm start
          wait-on: http://localhost:3000
  # install:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Cypress install
  #       uses: cypress-io/github-action@v6
  #       with:
  #         # Disable running of tests within install job
  #         runTests: false
  #         build: pnpm build
  #     - name: Save build folder
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: build
  #         if-no-files-found: error
  #         path: build
  # component:
  #   name: Component
  #   runs-on: ubuntu-22.04
  #   needs: install
  #   strategy:
  #     matrix:
  #       node-version: [18]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: pnpm/action-setup@v2
  #       with:
  #         version: 8
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "pnpm"
  #     - name: Install dependencies
  #       run: pnpm install
  #     - name: Run unit testing
  #       run: pnpm component:headless
  # e2e:
  #   name: End to End
  #   runs-on: ubuntu-22.04
  #   needs: install
  #   strategy:
  #     matrix:
  #       node-version: [18]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: pnpm/action-setup@v2
  #       with:
  #         version: 8
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "pnpm"
  #     - name: Install dependencies
  #       run: pnpm install
  #     - name: Run unit testing
  #       run: pnpm e2e:headless
